version: "3.9"
networks:
    traefik-public:
        external: true
    cosm-ia-net:
        external: true
services:
    cosm-ia-app:
        build: .
        container_name: cosmia-app
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ./.env:/var/www/html/.env
            - cosm-ia-storage:/var/www/html/storage
            - ./public/build:/var/www/html/public/build
            - cosm-ia-database:/var/www/html/database
        networks:
            - cosm-ia-net
            - traefik-public
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.cosm-ia.rule=Host(`cosmia.astucom.com`)
            - traefik.http.routers.cosm-ia.entrypoints=websecure
            - traefik.http.routers.cosm-ia.tls.certresolver=letsencrypt
            - traefik.http.services.cosm-ia.loadbalancer.server.port=80

    cosm-ia-npm-build:
        image: node:22-slim
        container_name: cosmia-npm-build
        working_dir: /app
        volumes:
            - .:/app
        profiles:
            - tools
        command: sh -c "npm install && npm run build"

volumes:
    cosm-ia-storage:
    cosm-ia-database:
